name: Check Environment Variables

on: [workflow_dispatch]

jobs:
  check-env:
    runs-on: ubuntu-latest
    steps:
      - name: Display Environment Variables
        run: |
          echo "TESTHENSUU: ${{ secrets.TESTHENSUU }}"
